# Generated by Django 5.1.4 on 2025-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0006_barberservice_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
