# Generated by Django 5.1.5 on 2025-04-07 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0007_barber_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barbertime',
            old_name='time_slots',
            new_name='time_slot',
        ),
        migrations.AddField(
            model_name='barber',
            name='time_slots',
            field=models.ManyToManyField(related_name='barbers', through='bs.BarberTime', to='bs.timeslot'),
        ),
        migrations.AlterField(
            model_name='barbertime',
            name='barber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bs.barber'),
        ),
    ]
