# Generated by Django 5.1.5 on 2025-04-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bs', '0008_rename_time_slots_barbertime_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barberservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_images/'),
        ),
    ]
